INSERT INTO agent_registry (id, name, cluster, llm_model, plan_ids) VALUES
('spec_analyst', 'Analista de Especificacoes', 'aec_core', 'deepseek-chat', ARRAY['aec_full','full_suite']),
('procurement', 'Agente de Compras', 'aec_core', 'deepseek-chat', ARRAY['aec_full','full_suite']),
('inventory', 'Gestao de Estoque', 'aec_core', 'deepseek-chat', ARRAY['aec_full','full_suite']),
('logistics', 'Logistica e Rastreamento', 'aec_core', 'deepseek-chat', ARRAY['aec_full','full_suite']),
('field_execution', 'Execucao em Campo', 'aec_core', 'deepseek-chat', ARRAY['aec_full','full_suite']),
('bim_coordinator', 'Coordenador BIM', 'aec_specialized', 'deepseek-chat', ARRAY['aec_full','full_suite']),
('requirements_analyst', 'Analise de Requisitos', 'aec_specialized', 'deepseek-chat', ARRAY['aec_full','full_suite']),
('engineering_assistant', 'Assistente de Engenharia', 'aec_specialized', 'deepseek-chat', ARRAY['aec_full','full_suite']),
('work_synopsis', 'Resumo de Tarefas', 'aec_specialized', 'deepseek-chat', ARRAY['aec_full','full_suite']),
('photo_intelligence', 'Inteligencia Visual de Obras', 'aec_compliance', 'deepseek-chat', ARRAY['aec_full','full_suite']),
('rfi_creation', 'Criacao de RFIs', 'aec_compliance', 'deepseek-chat', ARRAY['aec_full','full_suite']),
('compliance', 'Conformidade PGRS', 'aec_compliance', 'deepseek-chat', ARRAY['aec_full','full_suite']),
('nr1_psicossocial', 'NR-1 Riscos Psicossociais', 'regulatory', 'gemini-pro', ARRAY['compliance_essencial','regulatory_pro','full_suite']),
('tributario_cbs_ibs', 'Tributario CBS/IBS', 'regulatory', 'deepseek-chat', ARRAY['tributario_entrada','tributario_full','full_suite']),
('lgpd_operacional', 'LGPD Operacional', 'regulatory', 'gemini-pro', ARRAY['compliance_essencial','regulatory_pro','full_suite']),
('esg_ifrs', 'ESG IFRS S1/S2', 'regulatory', 'deepseek-chat', ARRAY['esg_carbon','regulatory_pro','full_suite']),
('inventario_carbono', 'Inventario de Carbono', 'regulatory', 'deepseek-chat', ARRAY['esg_carbon','full_suite']),
('escopo3_fornecedores', 'Escopo 3 Fornecedores', 'regulatory', 'deepseek-chat', ARRAY['esg_carbon','full_suite']),
('canal_denuncias', 'Canal de Denuncias', 'regulatory', 'gemini-pro', ARRAY['regulatory_pro','full_suite']),
('igualdade_salarial', 'Igualdade Salarial', 'regulatory', 'deepseek-chat', ARRAY['regulatory_pro','full_suite']),
('compliance_anticorrupcao', 'Compliance Anticorrupcao', 'regulatory', 'deepseek-chat', ARRAY['regulatory_pro','full_suite']),
('regulatory_analyst', 'Analista Regulatorio MS', 'microsoft', 'deepseek-chat', ARRAY['microsoft_pack','full_suite']),
('compliance_pm', 'Compliance PM', 'microsoft', 'deepseek-chat', ARRAY['microsoft_pack','full_suite']),
('channel_agent', 'Agente de Canal', 'microsoft', 'deepseek-chat', ARRAY['microsoft_pack','full_suite']),
('knowledge_agent', 'Agente de Conhecimento', 'microsoft', 'deepseek-chat', ARRAY['microsoft_pack','full_suite']),
('facilitator_agent', 'Agente Facilitador', 'microsoft', 'deepseek-chat', ARRAY['microsoft_pack','full_suite']),
('dev_experience', 'Developer Experience', 'microsoft', 'deepseek-chat', ARRAY['microsoft_pack','full_suite']),
('onboarding_funcionarios', 'Onboarding RH', 'cross_sell', 'deepseek-chat', ARRAY['cross_sell_harmony','full_suite']),
('atendimento_cliente_ptbr', 'Atendimento L1 PT-BR', 'cross_sell', 'deepseek-chat', ARRAY['atendimento_plus','full_suite']),
('conciliacao_financeira', 'Conciliacao Financeira', 'cross_sell', 'deepseek-chat', ARRAY['conciliacao_pro','full_suite'])
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, cluster=EXCLUDED.cluster, llm_model=EXCLUDED.llm_model, plan_ids=EXCLUDED.plan_ids;
