// AUTOGENERATED - DO NOT MODIFY

// View component imports — one per viewport declared in ui_extension.views
import AppView from '../src/views/AppView';

// Exposes the SDK version so the Dashboard can verify compatibility
export * from '@stripe/ui-extension-sdk/version';

// Named exports make each view component accessible to the Dashboard runtime

export { 
  AppView
 };

// Timestamp changes on every export, ensuring the dev server detects a rebuild
export const BUILD_TIME = '2026-06-26 21:22:36.6975119 -0300 -03 m=+28.367964301';

// App manifest — consumed by the Dashboard to configure the app
export default {
  "$schema": "https://stripe.com/stripe-app.schema.json",
  "distribution_type": "public",
  "icon": "./public/icon.png",
  "id": "com.globalengenharia.ecosystem-app",
  "name": "EcoSystem Compliance",
  "permissions": [
    {
      "permission": "customer_read",
      "purpose": "Identificar empresa para gerar score de compliance"
    },
    {
      "permission": "invoice_read",
      "purpose": "Verificar volume de transacoes para recomendar agentes"
    }
  ],
  "ui_extension": {
    "content_security_policy": {
      "connect-src": [
        "https://engenheiro-producao-ai.onrender.com/api/stripe/compliance-score"
      ],
      "purpose": "Conectar ao EcoSystem API para gerar score de compliance"
    },
    "views": [
      {
        "component": "AppView",
        "viewport": "stripe.dashboard.home.overview"
      }
    ]
  },
  "version": "1.0.1"
};
